site: CLM
url: "https://carloslucmat.github.io"
title: Carlos Lucas Mateo
description: Página personal
twitter:
  username: SanLucasMateo
  card: summary
  creator: Carlos Lucas Mateo
author:
  twitter: SanLucasMateo
  name: Carlos Lucas Mateo
  avatar:
  email: carloslucmat@politicas.unam.mx
  url: #yoururl
permalink: pretty

baseurl: "https://carloslucmat.github.io"

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
